# Generated by Django 4.1.3 on 2022-11-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwsiko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('opis', models.TextField()),
                ('premiera', models.DateTimeField(verbose_name='premiera')),
            ],
        ),
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwsiko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.IntegerField(choices=[(1, 'Tragiczny'), (2, 'Ujdzie'), (3, 'Sredni'), (4, 'Dobry'), (5, 'Swietny')])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaFilmowa.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='rezyser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaFilmowa.rezyser'),
        ),
    ]
