# Generated by Django 4.1.3 on 2022-11-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaFilmowa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='premiera',
            field=models.DateField(verbose_name='premiera'),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='wartosc',
            field=models.IntegerField(choices=[(1, 'Tragiczn'), (2, 'Ujdzie'), (3, 'Sredni'), (4, 'Dobry'), (5, 'Swietny')]),
        ),
    ]
