# Generated by Django 4.1.3 on 2022-12-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaFilmowa', '0004_film_ilosc_ocen_film_srednia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='ilosc_ocen',
        ),
        migrations.RemoveField(
            model_name='film',
            name='srednia',
        ),
    ]
